version: '3'
services:
  mongo:
    restart: always
    image: mongo:4.4.0
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: 5HaRSgjdwYFY7KwmQvhY30by
      MONGO_DEP_USERNAME: ebondidlrp
      MONGO_DEP_PASSWORD: lV6GhgvNgXyKvknJGr7ksYOH
      MONGO_DEP_DATABASE: ebondidlrp
    volumes: 
      - mongo:/data/db
      - ../files/create_user.sh:/docker-entrypoint-initdb.d/create_user.sh

volumes:
  mongo:

networks:
  default:
    external:
      name: ebond-idl-rp
