namespace: longhorn
role_service_name: longhorn
image:
  version: v1.3.2

backup:
  enabled: True
  name: s3-secret
  s3:
    endpoints: http://minio.svc.cluster.local
    bucket: longhorn
    access_key_id: "test"
    secret_access_key: "test"
    cert: ""

ingress:
  enabled: True
  domain_name: longhorn-{{ deplpy_domain_leaf | default("duke") }}.{{ deplpy_domain_root | default('draken.com')}}
  name: longhorn-ui
  type: traefik
  traefik:
    tls:
      enabled: false
      skip_verify: True
      client_cert: ""
      client_key: ""
  ingress-nginx:

helm_chart:
  name: longhorn
  version: 1.3.2
  log_format: json
  backup:
    enabled: True
    # name: "{{ secret.name }}"

