- name: Modify Host Name
  shell: hostnamectl set-hostname {{  hostname  }}
  when: hostname is defined

- name: Turn off the firewall
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Close selinux
  shell: "setenforce 0"
  failed_when: false

- name: Selinux modify enforcing
  lineinfile:
    dest: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=disabled'

- name: Configure remote host resolution
  template:
    src: hosts.j2
    dest: /etc/hosts
    mode: 0644
    backup: yes
  when: inventory_hostname in groups['all']
