---
- name: Offline environment cert-manager image import
  tags: ['k8tz', 'k8tz-iamge']
  block:
    - name: Create tools storage directory
      file:
        path: "/server/tools/{{ role_service_name }}/image"
        state: directory

    - name: copy image to remote host
      copy:
        src: "{{ image_path }}/{{ role_service_name }}/{{ role_service_name }}.{{ image.version }}.tar.gz"
        dest: "/server/tools/{{ role_service_name }}/image/{{ role_service_name }}.{{ image.version }}.tar.gz"
        owner: root
        group: root
        mode: 0644

    - name: image load
      community.docker.docker_image_load:
        path: "/server/tools/{{ role_service_name }}/image/{{ role_service_name }}.{{ image.version }}.tar.gz"
  when: network == false

- name: k8tz install
  tags: ['k8tz', 'k8tz-install']
  block:
    - name: create helm service directory
      file:
        path: "/server/tools/{{ role_service_name }}/helm"
        state: directory

    - name: Copy k8tz helm chart file
      copy:
        src: "{{ inventory_dir }}/roles/kubeadm/{{ role_service_name }}/files/{{ role_service_name }}-{{ helm_chart.version }}.tgz"
        dest: "/server/tools/{{ role_service_name }}/helm/{{ role_service_name }}-{{ helm_chart.version }}.tgz"
        owner: root
        group: root
        mode: 0644

    - name: Write k8tz template to file
      template:
        src: "{{ inventory_dir }}/roles/kubeadm/{{ role_service_name }}/templates/{{ item.src }}.j2"
        dest: "/server/tools/{{ role_service_name }}/helm/{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - { src: "values.yml", dest: "values.yml" }

    - name: Deploy k8tz chart from local path
      kubernetes.core.helm:
        name: "{{ helm_chart.name }}"
        chart_ref: "/server/tools/{{ role_service_name }}/helm/{{ role_service_name }}-{{ helm_chart.version }}.tgz"
        release_namespace: default
        values_files:
          - "/server/tools/{{ role_service_name }}/helm/values.yml"
  run_once: yes
  delegate_to: "{{ hostvars[groups['master'][0]].inventory_hostname }}"

- name: k8tz cli install 
  tags: ['k8tz', 'k8tz-cli']
  block:
    - name: debug
      debug:
        msg: "TODO"
  run_once: yes
  delegate_to: "{{ hostvars[groups['master'][0]].inventory_hostname }}"