- name: Create helm deploy directory
  file:
    path: "/server/tools/{{ role_service_name }}/helm/{{ cluster_type }}/operator"
    state: directory

- name: Copy pxc-operator helm chart file
  copy:
    src: "{{ inventory_dir }}/roles/kubeadm/{{ role_service_name }}/files/pxc-operator-{{ cluster_item.version }}.tgz"
    dest: "/server/tools/{{ role_service_name }}/helm/{{ cluster_type }}/operator/pxc-operator-{{ cluster_item.version }}.tgz"
    owner: root
    group: root
    mode: 0644

- name: Write pxc-operator template to file
  template:
    src: "{{ inventory_dir }}/roles/kubeadm/{{ role_service_name }}/templates/{{ cluster_type }}/{{ item.src }}.j2"
    dest: "/server/tools/{{ role_service_name }}/helm/{{ cluster_type }}/operator/{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: "pxc-operator-values.yml", dest: "operator.yml" }

- name: Deploy pxc-operator chart from local path
  kubernetes.core.helm:
    name: pxc-operator
    chart_ref: "/server/tools/{{ role_service_name }}/helm/{{ cluster_type }}/operator/pxc-operator-{{ cluster_item.version }}.tgz"
    release_namespace: "{{ deploy_item.namespace }}"
    create_namespace: yes
    values_files:
      - "/server/tools/{{ role_service_name }}/helm/{{ cluster_type }}/operator/operator.yml"