version: '3'
services:
  backend:
    restart: always
    container_name: backend
    image: 10.31.0.200:9077/ebondmedcore/ebond-idl-rp:deploy-4443af14
    command: /bin/bash -c /usr/src/backend/deploy/start_backend_server.sh
    ports:
      - 8100:8000
    volumes:
      - static:/usr/src/backend/static/
    environment:
      - COLUMNS=80
      - TZ=Asia/Shanghai
      - ENVIRONMENT=development
      - MYSQL_USER=ebondidlrp
      - MYSQL_PASSWORD=lWvF052Oar4ZcyfrS6jkVKZw
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=ebondidlrp
      - MYSQL_PORT=3306
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=ebond
      - RABBITMQ_PASSWORD=sfrCxnuX0Tj6TdYvjhGYjCIJ
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=KteOZa0UxZIQ3gaPfspJKqDg
      - MinIO_OCR_ENDPOINT=minio:9000
      - MinIO_OCR_ACCESS_KEY=ebond
      - MinIO_OCR_SECRET_KEY=rq6MjmEwueZCTk7TsBmYB6zK
      - MinIO_OCR_BUCKET=ebondidlrp
      - MinIO_OCR_Public_ENDPOINT=minio:9000
      - MONGO_USERNAME=ebondidlrp
      - MONGO_PASSWORD=lV6GhgvNgXyKvknJGr7ksYOH
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=ebondidlrp
      - SECURE=False
  backend_timing:
    restart: always
    container_name: backend_timing
    image: 10.31.0.200:9077/ebondmedcore/ebond-idl-rp:deploy-4443af14
    command: python manage.py runserver
    environment:
      - COLUMNS=80
      - TZ=Asia/Shanghai
      - ENVIRONMENT=development
      - MYSQL_USER=ebondidlrp
      - MYSQL_PASSWORD=lWvF052Oar4ZcyfrS6jkVKZw
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=ebondidlrp
      - MYSQL_PORT=3306
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=ebond
      - RABBITMQ_PASSWORD=sfrCxnuX0Tj6TdYvjhGYjCIJ
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=KteOZa0UxZIQ3gaPfspJKqDg
      - MinIO_OCR_ENDPOINT=minio:9000
      - MinIO_OCR_ACCESS_KEY=ebond
      - MinIO_OCR_SECRET_KEY=rq6MjmEwueZCTk7TsBmYB6zK
      - MinIO_OCR_BUCKET=ebondidlrp
      - MinIO_OCR_Public_ENDPOINT=minio:9000
      - MONGO_USERNAME=ebondidlrp
      - MONGO_PASSWORD=lV6GhgvNgXyKvknJGr7ksYOH
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=ebondidlrp
      - SECURE=False
  rabbitmq_client1:
    restart: always
    container_name: backend_rabbitmq
    image: 10.31.0.200:9077/ebondmedcore/ebond-idl-rp:deploy-4443af14
    command: /bin/bash -c /usr/src/backend/deploy/start_rabbitmq_client.sh
    environment:
      - COLUMNS=80
      - TZ=Asia/Shanghai
      - ENVIRONMENT=development
      - MYSQL_USER=ebondidlrp
      - MYSQL_PASSWORD=lWvF052Oar4ZcyfrS6jkVKZw
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=ebondidlrp
      - MYSQL_PORT=3306
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=ebond
      - RABBITMQ_PASSWORD=sfrCxnuX0Tj6TdYvjhGYjCIJ
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=KteOZa0UxZIQ3gaPfspJKqDg
      - MinIO_OCR_ENDPOINT=minio:9000
      - MinIO_OCR_ACCESS_KEY=ebond
      - MinIO_OCR_SECRET_KEY=rq6MjmEwueZCTk7TsBmYB6zK
      - MinIO_OCR_BUCKET=ebondidlrp
      - MinIO_OCR_Public_ENDPOINT=minio:9000
      - MONGO_USERNAME=ebondidlrp
      - MONGO_PASSWORD=lV6GhgvNgXyKvknJGr7ksYOH
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=ebondidlrp
      - SECURE=False
  rabbitmq_client2:
    restart: always
    container_name: backend_rabbitmq2
    image: 10.31.0.200:9077/ebondmedcore/ebond-idl-rp:deploy-4443af14
    command: /bin/bash -c /usr/src/backend/deploy/start_rabbitmq_client2.sh
    environment:
      - COLUMNS=80
      - TZ=Asia/Shanghai
      - ENVIRONMENT=development
      - MYSQL_USER=ebondidlrp
      - MYSQL_PASSWORD=lWvF052Oar4ZcyfrS6jkVKZw
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=ebondidlrp
      - MYSQL_PORT=3306
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=ebond
      - RABBITMQ_PASSWORD=sfrCxnuX0Tj6TdYvjhGYjCIJ
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=KteOZa0UxZIQ3gaPfspJKqDg
      - MinIO_OCR_ENDPOINT=minio:9000
      - MinIO_OCR_ACCESS_KEY=ebond
      - MinIO_OCR_SECRET_KEY=rq6MjmEwueZCTk7TsBmYB6zK
      - MinIO_OCR_BUCKET=ebondidlrp
      - MinIO_OCR_Public_ENDPOINT=minio:9000
      - MONGO_USERNAME=ebondidlrp
      - MONGO_PASSWORD=lV6GhgvNgXyKvknJGr7ksYOH
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=ebondidlrp
      - SECURE=False
  celery:
    restart: always
    container_name: backend_celery
    image: 10.31.0.200:9077/ebondmedcore/ebond-idl-rp:deploy-4443af14
    command: /bin/bash -c /usr/src/backend/deploy/start_celery_server.sh
    volumes:
      - static:/usr/src/backend/static/
    environment:
      - COLUMNS=80
      - TZ=Asia/Shanghai
      - ENVIRONMENT=development
      - MYSQL_USER=ebondidlrp
      - MYSQL_PASSWORD=lWvF052Oar4ZcyfrS6jkVKZw
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=ebondidlrp
      - MYSQL_PORT=3306
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=ebond
      - RABBITMQ_PASSWORD=sfrCxnuX0Tj6TdYvjhGYjCIJ
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=KteOZa0UxZIQ3gaPfspJKqDg
      - MinIO_OCR_ENDPOINT=minio:9000
      - MinIO_OCR_ACCESS_KEY=ebond
      - MinIO_OCR_SECRET_KEY=rq6MjmEwueZCTk7TsBmYB6zK
      - MinIO_OCR_BUCKET=ebondidlrp
      - MinIO_OCR_Public_ENDPOINT=minio:9000
      - MONGO_USERNAME=ebondidlrp
      - MONGO_PASSWORD=lV6GhgvNgXyKvknJGr7ksYOH
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=ebondidlrp
      - SECURE=False
  celery_task_result:
    restart: always
    container_name: backend_celery_task_result
    image: 10.31.0.200:9077/ebondmedcore/ebond-idl-rp:deploy-4443af14
    command: /bin/bash -c /usr/src/backend/deploy/start_celery_task_result.sh
    ports:
      - 5555:5555
    environment:
      - COLUMNS=80
      - TZ=Asia/Shanghai
      - ENVIRONMENT=development
      - MYSQL_USER=ebondidlrp
      - MYSQL_PASSWORD=lWvF052Oar4ZcyfrS6jkVKZw
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=ebondidlrp
      - MYSQL_PORT=3306
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=ebond
      - RABBITMQ_PASSWORD=sfrCxnuX0Tj6TdYvjhGYjCIJ
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=KteOZa0UxZIQ3gaPfspJKqDg
      - MinIO_OCR_ENDPOINT=minio:9000
      - MinIO_OCR_ACCESS_KEY=ebond
      - MinIO_OCR_SECRET_KEY=rq6MjmEwueZCTk7TsBmYB6zK
      - MinIO_OCR_BUCKET=ebondidlrp
      - MinIO_OCR_Public_ENDPOINT=minio:9000
      - MONGO_USERNAME=ebondidlrp
      - MONGO_PASSWORD=lV6GhgvNgXyKvknJGr7ksYOH
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=ebondidlrp
      - SECURE=False
  websocket:
    restart: always
    container_name: backend_websocket
    image: 10.31.0.200:9077/ebondmedcore/ebond-idl-rp:deploy-4443af14 
    command: python /usr/src/backend/mywebsocket/main.py
    ports:
      - 5679:5679
    environment:
      - COLUMNS=80
      - TZ=Asia/Shanghai
      - ENVIRONMENT=development
      - MYSQL_USER=ebondidlrp
      - MYSQL_PASSWORD=lWvF052Oar4ZcyfrS6jkVKZw
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=ebondidlrp
      - MYSQL_PORT=3306
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=ebond
      - RABBITMQ_PASSWORD=sfrCxnuX0Tj6TdYvjhGYjCIJ
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=KteOZa0UxZIQ3gaPfspJKqDg
      - MinIO_OCR_ENDPOINT=minio:9000
      - MinIO_OCR_ACCESS_KEY=ebond
      - MinIO_OCR_SECRET_KEY=rq6MjmEwueZCTk7TsBmYB6zK
      - MinIO_OCR_BUCKET=ebondidlrp
      - MinIO_OCR_Public_ENDPOINT=minio:9000
      - MONGO_USERNAME=ebondidlrp
      - MONGO_PASSWORD=lV6GhgvNgXyKvknJGr7ksYOH
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=ebondidlrp
      - SECURE=False

volumes:
  static:

networks:
  default:
    external:
      name: ebond-idl-rp
