- name: copy kubeadm init conf
  template:
    src: "{{ inventory_dir }}/roles/kubeadm/kubeadm/templates/kubeadm.yaml.j2"
    dest: "/server/tools/kubeadm/kubeadm.yaml"
    force: true
    owner: root
    group: root
    mode: 0644

- name: Kernel parameter adjustment
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
  loop: "{{ sysctl_args_conf }}"

- name: Disable swap
  command: swapoff -a

- name: Modified fatab comment to boot automatically
  shell: >
    sed -ri "s%(^/.*|^UUID.*)(swap.*)%# \1\2%g" /etc/fstab
