# 是否开启harbor
harbor_run: false
harbor_url: "10.31.0.200:9077"
# 登陆harbor支持多
# TODO 支持多
# docker_repositories: [
#   { username: "admin", password: "Harbor12345", registry_url: "10.31.0.200:9077", insecure: false }
# ]

docker_repositories: 
  - name: Harbor
    username: admin
    password: Harbor12345
    registry_url: 10.31.0.200:9077
    insecure: false


# gpu节点配置
docker_daemon_gpu: {  
                    'default-runtime': 'nvidia',
                        'runtimes': {
                          'nvidia': { 
                              'path': 'nvidia-container-runtime',
                              'runtimeArgs': []
                          }
                        } 
                   }