- name: Write cert-manager template to file
  template:
    src: "{{ inventory_dir }}/roles/kubeadm/cert-manager/templates/issue/{{ item.src }}.j2"
    dest: "/server/tools/{{ role_service_name }}/{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: "mtls.yml", dest: "{{ args_deploy.name }}-mtls.yml" }

- name: Create namespace
  shell: "kubectl create ns {{ args_deploy.namespace }}"
  failed_when: false

- name: Create tls certificate issuer
  kubernetes.core.k8s:
    state: present
    src: "/server/tools/{{ args_role_service_name }}/{{ item.src }}"
  with_items:
    - { src: "{{  args_deploy.name }}-mtls.yml" }