version: '3'
services:
  minio:
    restart: always
    image: minio/minio:RELEASE.2022-08-08T18-34-09Z
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MINIO_ACCESS_KEY: ebond
      MINIO_SECRET_KEY: rq6MjmEwueZCTk7TsBmYB6zK
    command: server --console-address ':9001' --address ':9000' /data
    volumes:
      - minio:/data
      - ../files/localtime:/etc/localtime 

volumes:
  minio:

networks:
  default:
    external:
      name: ebond-idl-rp

