---
- name: Offline environment cert-manager image import
  tags: ['traefik', 'traefik-iamge']
  block:
    - name: Create tools storage directory
      file:
        path: "/server/tools/{{ role_service_name }}/image"
        state: directory

    - name: copy image to remote host
      copy:
        src: "{{ image_path }}/{{ role_service_name }}/{{ role_service_name }}.{{ image.version }}.tar.gz"
        dest: "/server/tools/{{ role_service_name }}/image/{{ role_service_name }}.{{ image.version }}.tar.gz"
        owner: root
        group: root
        mode: 0644

    - name: image load
      community.docker.docker_image_load:
        path: "/server/tools/{{ role_service_name }}/image/{{ role_service_name }}.{{ image.version }}.tar.gz"
  when: network == false

- name: traefik install
  tags: ['traefik', 'traefik-install']
  block:
    - name: create helm service directory
      file:
        path: "/server/tools/{{ role_service_name }}/helm"
        state: directory

    - name: Add label to node
      shell: "kubectl label node {{ item.node.split(',')[0]|default('none') }} {{ service.lables }} --overwrite"
      loop: "{{ service.metadata }}"
      when: 
        - service.metadata is defined
        - service.lables != ""
        
    - name: Copy traefik helm chart file
      copy:
        src: "{{ inventory_dir }}/roles/kubeadm/{{ role_service_name }}/files/{{ role_service_name }}-{{ helm_chart.version }}.tgz"
        dest: "/server/tools/{{ role_service_name }}/helm/{{ role_service_name }}-{{ helm_chart.version }}.tgz"
        owner: root
        group: root
        mode: 0644

    - name: Write traefik template to file
      template:
        src: "{{ inventory_dir }}/roles/kubeadm/{{ role_service_name }}/templates/{{ item.src }}.j2"
        dest: "/server/tools/{{ role_service_name }}/helm/{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - { src: "values.yml", dest: "values.yml" }

    - name: Deploy traefik chart from local path
      kubernetes.core.helm:
        name: "{{ helm_chart.name }}"
        chart_ref: "/server/tools/{{ role_service_name }}/helm/{{ role_service_name }}-{{ helm_chart.version }}.tgz"
        release_namespace: "{{ namespace }}"
        create_namespace: yes
        values_files:
          - "/server/tools/{{ role_service_name }}/helm/values.yml"
  run_once: yes
  delegate_to: "{{ hostvars[groups['master'][0]].inventory_hostname }}"

- name: traefik dashboard
  tags: ['traefik', 'traefik-dashboard']
  block:
    - name: copy traefik dashboard deploy file
      template:
        src: "{{ inventory_dir }}/roles/kubeadm/{{ role_service_name }}/templates/dashboard.yml.j2"
        dest: "/server/tools/{{ role_service_name }}/dashboard.yml"
        owner: root
        group: root
        mode: 0644

    - name: deploy dashboard ingressroute
      kubernetes.core.k8s:
        state: present
        src: "/server/tools/{{ role_service_name }}/dashboard.yml"
  run_once: yes
  delegate_to: "{{ hostvars[groups['master'][0]].inventory_hostname }}"