- name: install docker
  block:
    - name: install python3-pip
      yum:
        name: python3-pip
        state: present

    - name: install docker
      yum:
        name: docker-ce
        state: present
      register: docker_install_info

  rescue:
    - name: remove selinux-policy
      shell: yum remove selinux-policy -y
      when: docker_install_info.failed == true
      
    - name: retry install docker
      yum:
        name: docker-ce
        state: present
