version: '3'
services:
  redis:
    container_name: redis
    image: redis:6.0.7
    restart: always
    ports:
      - 6379:6379
    command: redis-server /etc/conf/redis.conf
    volumes:
      - redis:/data
      - ../files/redis.conf:/etc/conf/redis.conf
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
volumes:
  redis:

networks:
  default:
    external:
      name: ebond-idl-rp
