- name: Initialize kubeadm config
  include_tasks: "{{ inventory_dir }}/roles/kubeadm/kubeadm/tasks/install/init/config.yml"

- name: shell
  shell: "{{ kubeadm_token.stdout }}"

- name: kubelet Start up automatically
  service: name=kubelet state=started enabled=yes

- name: Populate service facts
  service_facts:

- name: Monitor the 10248 port until the waiting timeout
  wait_for:
    port: 10248
    delay: 10
    timeout: 60
    state: started
